name: gitpod_dart
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/DanTup/gitpod-dart
author: Danny Tuppeny <danny@tuppeny.com>

environment:
  sdk: ^3.5.0-202.0.dev

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
