name: gitpod_dart
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/DanTup/gitpod-dart

environment:
  sdk: ^3.4.3-202.0.dev

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
